"""
End-to-end integration tests.

These tests exercise complete workflows from key generation through
encryption / signing / verification / migration without any mocking.
They use only the classical components (X25519, Ed25519) so they run
without liboqs installed. Tests that exercise actual ML-KEM / ML-DSA
are marked @pytest.mark.requires_liboqs.

The goal here is to prove the modules compose correctly — that a key
generated by HybridKEM can actually seal an Envelope, that a JWT signed
by JWTSigner can be verified by JWTVerifier, that the scanner findings
feed correctly into the compliance report.
"""

from __future__ import annotations

import json
import os
import sys
import warnings

import pytest

from quantum_safe.audit import AuditPolicy, Auditor, NISTComplianceChecker, SBOMEnricher
from quantum_safe.backends.base import AbstractKEMBackend, AbstractSignatureBackend
from quantum_safe.audit.sbom import PQCReadiness
from quantum_safe.kem.hybrid import HybridKEM
from quantum_safe.migrate import MigrationStateManager, Scanner, Upgrader
from quantum_safe.migrate.scanner import Severity
from quantum_safe.protocols.envelope import Envelope, SealedMessage
from quantum_safe.protocols.jwt import JWTSigner, JWTVerifier
from quantum_safe.protocols.tls import HybridTLSConfig, configure_hybrid_context
from quantum_safe.signatures.hybrid import HybridSign
from quantum_safe.signatures.core import Sign
from quantum_safe.types import (
    HybridCipherText, KeyPair, MigrationState, PublicKey, SecretKey, SharedSecret
)
from quantum_safe.exceptions import VerificationError, UnsupportedAlgorithm


# ---------------------------------------------------------------------------
# Helpers — mock backends for classical-only path
# ---------------------------------------------------------------------------


class _MockKEMBackend(AbstractKEMBackend):
    name = "mock"
    def keygen(self, a): return b"\xAA" * 1184, b"\xBB" * 2400
    def encapsulate(self, a, p): return b"\xCC" * 1088, b"\xDD" * 32
    def decapsulate(self, a, s, c): return b"\xDD" * 32
    def is_available(self): return True
    def supported_algorithms(self): return []


class _MockSigBackend(AbstractSignatureBackend):
    name = "mock"
    def keygen(self, a): return b"\xAA" * 1952, b"\xBB" * 4000
    def sign(self, a, sk, msg, ctx=b""): return b"\xCC" * 3293
    def verify(self, a, pk, msg, sig, ctx=b""): return len(sig) == 3293
    def is_available(self): return True
    def supported_algorithms(self): return []


def _mock_kem():
    k = HybridKEM.__new__(HybridKEM)
    k._classical = "X25519"
    k._pqc = "ML-KEM-768"
    k._algorithm = "X25519+ML-KEM-768"
    k._backend = _MockKEMBackend()
    return k


def _mock_sign():
    hs = HybridSign.__new__(HybridSign)
    hs._classical = "Ed25519"
    hs._pqc = "ML-DSA-65"
    hs._algorithm = "Ed25519+ML-DSA-65"
    hs._hedged = True
    hs._backend = _MockSigBackend()
    return hs


# ---------------------------------------------------------------------------
# Workflow 1: key generation → serialization → round-trip
# ---------------------------------------------------------------------------


class TestKeyLifecycle:
    """A key generated in one place must be usable in another."""

    def test_kem_keypair_pem_survives_serialization(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()

        # Serialize public key
        pub_pem = kp.public.to_pem()
        pub_cbor = kp.public.to_cbor()
        pub_jwk = kp.public.to_jwk()

        # Deserialize all three formats
        pub_from_pem = PublicKey.from_pem(pub_pem)
        pub_from_cbor = PublicKey.from_cbor(pub_cbor)
        pub_from_jwk = PublicKey.from_jwk(pub_jwk)

        # All deserialized keys should be equal
        assert pub_from_pem.raw_bytes == kp.public.raw_bytes
        assert pub_from_cbor.raw_bytes == kp.public.raw_bytes
        assert pub_from_jwk.raw_bytes == kp.public.raw_bytes

    def test_signing_keypair_round_trip(self):
        signer = _mock_sign()
        kp = signer.generate_keypair()

        pub_pem = kp.public.to_pem()
        pub2 = PublicKey.from_pem(pub_pem)
        assert pub2.algorithm == kp.public.algorithm
        assert pub2.raw_bytes == kp.public.raw_bytes

    def test_key_fingerprints_stable(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        fp1 = kp.public.fingerprint()
        fp2 = kp.public.fingerprint()
        assert fp1 == fp2
        assert len(fp1) == 64  # sha256 hex

    def test_keypair_bundle_round_trip(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        bundle = kp.to_cbor_bundle()
        kp2 = KeyPair.from_cbor_bundle(bundle)
        assert kp2.public.raw_bytes == kp.public.raw_bytes
        assert kp2.secret.raw_bytes == kp.secret.raw_bytes


# ---------------------------------------------------------------------------
# Workflow 2: full Envelope encrypt → serialize → decrypt cycle
# ---------------------------------------------------------------------------


class TestEnvelopeWorkflow:
    """Envelope must survive network serialization."""

    def test_seal_serialize_open(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()

        # Sender: seal
        plaintext = b"confidential payload"
        sealed = Envelope.seal(plaintext, kp.public, kem=kem)

        # Wire: serialize to bytes
        wire = sealed.to_bytes()
        assert len(wire) > 0

        # Receiver: deserialize and open
        sealed2 = SealedMessage.from_bytes(wire)
        recovered = Envelope.open(sealed2, kp.secret, kem=kem)

        assert recovered == plaintext

    def test_seal_hex_round_trip(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        sealed = Envelope.seal(b"hex payload", kp.public, kem=kem)
        hex_str = sealed.to_hex()
        assert isinstance(hex_str, str)
        sealed2 = SealedMessage.from_hex(hex_str)
        recovered = Envelope.open(sealed2, kp.secret, kem=kem)
        assert recovered == b"hex payload"

    def test_envelope_with_aad(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        sealed = Envelope.seal(
            b"protected payload",
            kp.public,
            aad=b"recipient-id:user-42",
            kem=kem,
        )
        assert sealed.aad == b"recipient-id:user-42"
        recovered = Envelope.open(sealed, kp.secret, kem=kem)
        assert recovered == b"protected payload"

    def test_envelope_large_payload(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        large = os.urandom(1024 * 64)  # 64 KB
        sealed = Envelope.seal(large, kp.public, kem=kem)
        recovered = Envelope.open(sealed, kp.secret, kem=kem)
        assert recovered == large

    def test_envelope_inspect_no_secrets(self):
        kem = _mock_kem()
        kp = kem.generate_keypair()
        sealed = Envelope.seal(b"secret", kp.public, kem=kem)
        info = sealed.inspect()
        assert "algorithm" in info
        assert "secret" not in str(info).lower()
        assert info["kem_ct_size"] > 0


# ---------------------------------------------------------------------------
# Workflow 3: JWT sign → verify → claim validation
# ---------------------------------------------------------------------------


class TestJWTWorkflow:
    """JWT tokens must round-trip with real Ed25519 verification."""

    def _make_pair(self, issuer="test.example.com"):
        hs = _mock_sign()
        kp = hs.generate_keypair()

        signer = JWTSigner.__new__(JWTSigner)
        signer._keypair = kp
        signer._hedged = True
        signer._issuer = issuer
        signer._algorithm = "Ed25519+ML-DSA-65"
        signer._signer = hs

        verifier = JWTVerifier.__new__(JWTVerifier)
        verifier._public_key = kp.public
        verifier._issuer = issuer
        verifier._audience = None
        verifier._algorithm = "Ed25519+ML-DSA-65"
        verifier._verifier = hs

        return signer, verifier

    def test_sign_and_verify(self):
        signer, verifier = self._make_pair()
        token = signer.sign({"sub": "user123", "role": "admin"})
        claims = verifier.verify(token)
        assert claims["sub"] == "user123"
        assert claims["role"] == "admin"
        assert claims["iss"] == "test.example.com"

    def test_token_has_three_parts(self):
        signer, _ = self._make_pair()
        token = signer.sign({"sub": "u"})
        assert token.count(".") == 2

    def test_tampered_payload_rejected(self):
        import base64
        signer, verifier = self._make_pair()
        token = signer.sign({"sub": "user"})
        header, _, sig = token.split(".")
        fake_payload = base64.urlsafe_b64encode(
            json.dumps({"sub": "admin", "iss": "test.example.com",
                        "iat": 9999999999}).encode()
        ).rstrip(b"=").decode()
        tampered = f"{header}.{fake_payload}.{sig}"
        with pytest.raises(VerificationError):
            verifier.verify(tampered)

    def test_expired_token_rejected(self):
        import time
        signer, verifier = self._make_pair()
        token = signer.sign({"sub": "u", "exp": int(time.time()) - 200})
        with pytest.raises(VerificationError):
            verifier.verify(token)

    def test_zero_expires_in_omits_exp(self):
        signer, verifier = self._make_pair()
        token = signer.sign({"sub": "u"}, expires_in=0)
        payload_b64 = token.split(".")[1]
        padding = "=" * (-len(payload_b64) % 4)
        import base64
        claims_raw = json.loads(base64.urlsafe_b64decode(payload_b64 + padding))
        assert "exp" not in claims_raw


# ---------------------------------------------------------------------------
# Workflow 4: X.509 certificate generation
# ---------------------------------------------------------------------------


class TestX509Workflow:
    def test_cert_generation_and_inspection(self):
        from quantum_safe.protocols.x509 import (
            HybridCertificateBuilder, generate_classical_keypair_for_cert
        )
        from cryptography import x509 as cx509
        from cryptography.hazmat.backends import default_backend

        classical_key = generate_classical_keypair_for_cert("Ed25519")
        signer = _mock_sign()
        hybrid_kp = signer.generate_keypair()

        builder = HybridCertificateBuilder(
            subject_cn="integration.test.internal",
            classical_private_key=classical_key,
            pqc_keypair=hybrid_kp,
            validity_days=90,
            dns_names=["integration.test.internal", "alt.test.internal"],
        )
        cert_pem, cosig = builder.build(signer=signer)

        assert b"BEGIN CERTIFICATE" in cert_pem
        assert len(cosig) > 0

        cert = cx509.load_pem_x509_certificate(cert_pem, default_backend())
        cn = cert.subject.get_attributes_for_oid(
            cx509.oid.NameOID.COMMON_NAME
        )[0].value
        assert cn == "integration.test.internal"


# ---------------------------------------------------------------------------
# Workflow 5: scanner → auditor → compliance → SBOM pipeline
# ---------------------------------------------------------------------------


class TestAuditPipeline:
    """Scanning findings must flow correctly through audit and compliance."""

    _RSA_SOURCE = (
        "from cryptography.hazmat.primitives.asymmetric import rsa\n"
        "key = rsa.generate_private_key(65537, 2048)\n"
        "from cryptography.hazmat.primitives.asymmetric import padding\n"
        "enc = padding.OAEP(mgf=None, algorithm=None, label=None)\n"
    )

    def test_scanner_to_auditor_to_compliance(self):
        # Step 1: scan
        scan = Scanner.scan_source(self._RSA_SOURCE, filename="app.py")
        assert scan.has_blocking_findings

        # Step 2: audit
        report = Auditor.audit_source(self._RSA_SOURCE, policy=AuditPolicy())
        assert not report.passed
        assert report.policy_violations

        # Step 3: NIST compliance
        compliance = NISTComplianceChecker.check(scan, target="app.py")
        from quantum_safe.audit.compliance import ComplianceLevel
        assert compliance.overall_level == ComplianceLevel.NON_COMPLIANT
        assert compliance.non_compliant_controls

        # Step 4: SARIF output is valid JSON
        sarif = json.loads(json.dumps(report.to_sarif()))
        assert sarif["version"] == "2.1.0"

    def test_clean_source_passes_all_checks(self):
        src = "from quantum_safe import HybridKEM, HybridSign\n"
        scan = Scanner.scan_source(src)
        assert not scan.has_blocking_findings

        report = Auditor.audit_source(src)
        assert report.passed

    def test_sbom_pipeline(self):
        sbom = {
            "bomFormat": "CycloneDX",
            "specVersion": "1.4",
            "version": 1,
            "components": [
                {"name": "cryptography", "version": "44.0.5"},
                {"name": "pycryptodome", "version": "3.20.0"},
                {"name": "quantum-safe", "version": "0.1.0"},
            ],
        }
        enriched, assessments = SBOMEnricher.enrich(sbom)
        qs_a = next(a for a in assessments if a.name == "quantum-safe")
        pycrypto_a = next(a for a in assessments if a.name == "pycryptodome")
        assert qs_a.readiness == PQCReadiness.READY
        assert pycrypto_a.readiness == PQCReadiness.NOT_READY
        assert json.dumps(enriched)  # must be JSON-serialisable


# ---------------------------------------------------------------------------
# Workflow 6: migration state machine + upgrader pipeline
# ---------------------------------------------------------------------------


class TestMigrationWorkflow:
    """Key upgrade and state tracking must compose end-to-end."""

    def test_classical_key_to_hybrid_and_track(self):
        # Simulate a classical X25519 key being upgraded
        classical_pub = os.urandom(32)
        classical_sec = os.urandom(32)

        import quantum_safe.backends as _bk
        orig = _bk.get_kem_backend
        _bk.get_kem_backend = lambda name="auto": _MockKEMBackend()

        try:
            result = Upgrader.upgrade_kem_key(
                classical_secret_bytes=classical_sec,
                classical_public_bytes=classical_pub,
                classical_algorithm="X25519",
                target_pqc="ML-KEM-768",
            )
        finally:
            _bk.get_kem_backend = orig

        assert result.new_algorithm == "X25519+ML-KEM-768"
        assert result.backward_compat
        new_kp = result.new_keypair

        # Track in state machine
        store = {}
        mgr = MigrationStateManager(store)
        key_id = new_kp.public.fingerprint()[:16]

        rec = mgr.transition(
            key_id=key_id,
            from_state=MigrationState.CLASSICAL_ONLY,
            to_state=MigrationState.HYBRID_TRANSITION,
            algorithm=new_kp.algorithm,
            actor="integration-test",
        )

        assert mgr.get_current_state(key_id) == MigrationState.HYBRID_TRANSITION
        history = mgr.get_history(key_id)
        assert len(history) == 1
        assert history[0].actor == "integration-test"

    def test_upgrader_describe_key(self):
        classical_pk = PublicKey(
            raw=b"\x01" * 32,
            algorithm="X25519",
            migration_state=MigrationState.CLASSICAL_ONLY,
        )
        classical_sk = SecretKey(
            raw=b"\x02" * 32,
            algorithm="X25519",
            migration_state=MigrationState.CLASSICAL_ONLY,
        )
        kp = KeyPair(public=classical_pk, secret=classical_sk)
        desc = Upgrader.describe_key(kp)
        assert desc["needs_upgrade"] is True
        assert desc["migration_state"] == "classical_only"
        assert "Upgrade" in desc["recommendation"]


# ---------------------------------------------------------------------------
# Workflow 7: TLS configuration
# ---------------------------------------------------------------------------


class TestTLSWorkflow:
    def test_configure_tls_context(self):
        import ssl
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            configure_hybrid_context(ctx, HybridTLSConfig())
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_3

    def test_hybrid_config_validation(self):
        with pytest.raises(ValueError):
            HybridTLSConfig(kem_algorithm="INVALID+ALGO")


# ---------------------------------------------------------------------------
# Workflow 8: shared secret derive_key
# ---------------------------------------------------------------------------


class TestSharedSecretWorkflow:
    def test_two_keys_from_same_secret(self):
        from quantum_safe.types import SharedSecret
        ss = SharedSecret(os.urandom(32), "X25519+ML-KEM-768", is_hybrid=True)
        enc_key = ss.derive_key(32, info=b"encryption")
        mac_key = ss.derive_key(32, info=b"authentication")
        assert enc_key != mac_key
        assert len(enc_key) == 32
        assert len(mac_key) == 32

    def test_derive_key_deterministic(self):
        from quantum_safe.types import SharedSecret
        raw = os.urandom(32)
        ss1 = SharedSecret(raw, "test")
        ss2 = SharedSecret(raw, "test")
        assert ss1.derive_key(32, info=b"test") == ss2.derive_key(32, info=b"test")


# ---------------------------------------------------------------------------
# Integration tests that require liboqs
# ---------------------------------------------------------------------------


@pytest.mark.requires_liboqs
class TestWithRealBackend:
    def test_hybrid_kem_full_cycle(self):
        kem = HybridKEM()
        kp = kem.generate_keypair()
        hct, ss1 = kem.encapsulate(kp.public)
        ss2 = kem.decapsulate(kp.secret, hct)
        assert ss1 == ss2
        assert ss1.is_hybrid

    def test_hybrid_sign_full_cycle(self):
        signer = HybridSign()
        kp = signer.generate_keypair()
        sm = signer.sign(b"integration test message", kp.secret, context=b"test-v1")
        signer.verify(sm, kp.public)

    def test_envelope_with_real_kem(self):
        kem = HybridKEM()
        kp = kem.generate_keypair()
        sealed = Envelope.seal(b"real payload", kp.public)
        recovered = Envelope.open(sealed, kp.secret)
        assert recovered == b"real payload"

    def test_jwt_with_real_backend(self):
        signer_obj = HybridSign()
        kp = signer_obj.generate_keypair()
        jwt_signer = JWTSigner(kp, issuer="real-integration")
        token = jwt_signer.sign({"sub": "real-user"})
        jwt_verifier = JWTVerifier(kp.public, issuer="real-integration")
        claims = jwt_verifier.verify(token)
        assert claims["sub"] == "real-user"

    def test_scanner_finds_rsa_in_tempfile(self, tmp_path):
        f = tmp_path / "legacy.py"
        f.write_text(
            "from cryptography.hazmat.primitives.asymmetric import rsa\n"
            "key = rsa.generate_private_key(65537, 2048)\n"
        )
        report = Auditor.audit(tmp_path, policy=AuditPolicy())
        assert not report.passed
